# 개개 player의 seat_no
SEAT_NO_MAX_EXCLUSIVE = 8
SEAT_NO_MIN = 0

# seat의 개수
SEAT_MIN = 4
SEAT_MAX_EXCLUSIVE = 8


# CASE 관련 상수
INITIAL_SCHEMA_VERSION = 1
INITIAL_SNAPSHOT_NO = 1
INITIAL_ROUND_NO = 1
INITIAL_SEQ_IN_ROUND = 1
INITIAL_PHASE_NO_IN_ROUND = 1
