"""add phases table

Revision ID: 073a1b1e3e6f
Revises: f28741778445
Create Date: 2026-03-21 11:43:14.961446

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "073a1b1e3e6f"
down_revision: Union[str, Sequence[str], None] = "f28741778445"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("round_no", sa.Integer(), nullable=False),
        sa.Column("seq_in_round", sa.Integer(), nullable=False),
        sa.Column(
            "phase_type",
            sa.Enum("NIGHT", "DISCUSS", "VOTE", name="phase_type"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "round_no", "seq_in_round", name="uq_case_round_seq"),
    )
    op.create_index(op.f("ix_phases_case_id"), "phases", ["case_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phases_case_id"), table_name="phases")
    op.drop_table("phases")
    # ### end Alembic commands ###
