"""add room name

Revision ID: a987840a0e7e
Revises: 658f74da6d22
Create Date: 2026-02-26 15:08:29.527342

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a987840a0e7e"
down_revision: Union[str, Sequence[str], None] = "658f74da6d22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
