"""change room_name to name

Revision ID: d3181900b419
Revises: a987840a0e7e
Create Date: 2026-03-12 18:22:16.524879

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3181900b419"
down_revision: Union[str, Sequence[str], None] = "a987840a0e7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "room_name", new_column_name="name")
    op.execute("ALTER TABLE rooms RENAME CONSTRAINT rooms_room_name_key TO rooms_name_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "name", new_column_name="room_name")
    op.execute("ALTER TABLE rooms RENAME CONSTRAINT rooms_name_key TO rooms_room_name_key")
    # ### end Alembic commands ###
