"""add case-related models

Revision ID: f28741778445
Revises: d3181900b419
Create Date: 2026-03-17 16:00:17.164956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f28741778445"
down_revision: Union[str, Sequence[str], None] = "d3181900b419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("host_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "ENDED", "INTERRUPTED", name="case_status_"),
            nullable=False,
        ),
        sa.Column("current_round_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'RUNNING' AND ended_at IS NULL) OR "
            "(status = 'ENDED' AND ended_at IS NOT NULL)",
            name="ck_cases_status_ended_at_consistency",
        ),
        sa.CheckConstraint("current_round_no >= 1", name="ck_cases_round_no_positive"),
        sa.ForeignKeyConstraint(["host_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cases_room_id_status", "cases", ["room_id", "status"], unique=False)
    op.create_index(
        "uq_cases_room_running",
        "cases",
        ["room_id"],
        unique=True,
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.create_table(
        "case_players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("seat_no", sa.Integer(), nullable=False),
        sa.Column("life_left", sa.Integer(), nullable=False),
        sa.Column("vote_tokens", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "life_left >= 0 AND life_left <= 2", name="ck_case_players_life_left_range"
        ),
        sa.CheckConstraint("seat_no >= 0 AND seat_no < 8", name="ck_case_players_seat_no_range"),
        sa.CheckConstraint(
            "vote_tokens >= 0 AND vote_tokens <= 4", name="ck_case_players_vote_tokens_range"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "seat_no", name="uq_case_players_case_seat"),
        sa.UniqueConstraint("case_id", "user_id", name="uq_case_players_case_user"),
    )
    op.create_index(op.f("ix_case_players_case_id"), "case_players", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_players_user_id"), "case_players", ["user_id"], unique=False)
    op.create_table(
        "case_snapshot_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_no", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "schema_version >= 1", name="ck_case_snapshot_history_schema_version_positive"
        ),
        sa.CheckConstraint(
            "snapshot_no >= 1", name="ck_case_snapshot_history_snapshot_no_positive"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "snapshot_no", name="uq_case_snapshot_history_case_snapshot_no"
        ),
    )
    op.create_index(
        op.f("ix_case_snapshot_history_case_id"), "case_snapshot_history", ["case_id"], unique=False
    )
    op.create_index(
        "ix_case_snapshot_history_case_id_snapshot_no_desc",
        "case_snapshot_history",
        ["case_id", "snapshot_no"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_case_snapshot_history_case_id_snapshot_no_desc", table_name="case_snapshot_history"
    )
    op.drop_index(op.f("ix_case_snapshot_history_case_id"), table_name="case_snapshot_history")
    op.drop_table("case_snapshot_history")
    op.drop_index(op.f("ix_case_players_user_id"), table_name="case_players")
    op.drop_index(op.f("ix_case_players_case_id"), table_name="case_players")
    op.drop_table("case_players")
    op.drop_index(
        "uq_cases_room_running", table_name="cases", postgresql_where=sa.text("status = 'RUNNING'")
    )
    op.drop_index("ix_cases_room_id_status", table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
