"""add case_actions,vote_phase_states tables

Revision ID: fbacadb30ed4
Revises: 073a1b1e3e6f
Create Date: 2026-03-26 19:59:12.779563

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbacadb30ed4"
down_revision: Union[str, Sequence[str], None] = "073a1b1e3e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("phase_id", sa.UUID(), nullable=False),
        sa.Column("actor_player_id", sa.UUID(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "NIGHT_ACTION_RED_VOTE",
                "NIGHT_ACTION_SKIP",
                "DISCUSS_ACTION_INIT_BLUE_VOTE",
                "DISCUSS_ACTION_SKIP",
                "VOTE_ACTION_YES",
                "VOTE_ACTION_NO",
                "VOTE_ACTION_SKIP",
                name="action_type_",
            ),
            nullable=False,
        ),
        sa.Column("night_target_seat_no", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "night_target_seat_no >= 0 AND night_target_seat_no < 8",
            name="ck_case_actions_night_target_seat_no_range",
        ),
        sa.ForeignKeyConstraint(["actor_player_id"], ["case_players.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["phase_id"], ["phases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phase_id", "actor_player_id", name="uq_case_actions_phase_actor"),
    )
    op.create_index(op.f("ix_case_actions_case_id"), "case_actions", ["case_id"], unique=False)
    op.create_index(
        "ix_case_actions_case_phase", "case_actions", ["case_id", "phase_id"], unique=False
    )
    op.create_index(op.f("ix_case_actions_phase_id"), "case_actions", ["phase_id"], unique=False)
    op.create_table(
        "vote_phase_states",
        sa.Column("phase_id", sa.UUID(), nullable=False),
        sa.Column("target_seat_no", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "target_seat_no >= 0 AND target_seat_no < 8",
            name="ck_vote_phase_states_target_seat_no_range",
        ),
        sa.ForeignKeyConstraint(["phase_id"], ["phases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("phase_id"),
    )
    op.create_index(
        op.f("ix_vote_phase_states_phase_id"), "vote_phase_states", ["phase_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vote_phase_states_phase_id"), table_name="vote_phase_states")
    op.drop_table("vote_phase_states")
    op.drop_index(op.f("ix_case_actions_phase_id"), table_name="case_actions")
    op.drop_index("ix_case_actions_case_phase", table_name="case_actions")
    op.drop_index(op.f("ix_case_actions_case_id"), table_name="case_actions")
    op.drop_table("case_actions")
    # ### end Alembic commands ###
