// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";
import type { AxiosError } from "axios";

import { client } from "../client.gen";
import {
  blueVoteApiV1CasesCurrentPhasesCurrentBlueVotePost,
  caseStartApiV1RoomsCurrentCaseStartPost,
  forceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPost,
  guestLoginApiV1AuthGuestLoginPost,
  healthApiHealthGet,
  initBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePost,
  joinRoomApiV1RoomsRoomIdJoinPost,
  kickUserApiV1RoomsCurrentUsersUserIdKickPost,
  leaveRoomApiV1RoomsCurrentLeavePost,
  logoutApiV1AuthLogoutPost,
  type Options,
  redVoteApiV1CasesCurrentPhasesCurrentRedVotePost,
  roomStateSseRtV1SseRoomsCurrentGet,
} from "../sdk.gen";
import type {
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData,
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostError,
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponse,
  CaseStartApiV1RoomsCurrentCaseStartPostData,
  CaseStartApiV1RoomsCurrentCaseStartPostError,
  CaseStartApiV1RoomsCurrentCaseStartPostResponse,
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData,
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostError,
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponse,
  GuestLoginApiV1AuthGuestLoginPostData,
  GuestLoginApiV1AuthGuestLoginPostError,
  GuestLoginApiV1AuthGuestLoginPostResponse,
  HealthApiHealthGetData,
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData,
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostError,
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponse,
  JoinRoomApiV1RoomsRoomIdJoinPostData,
  JoinRoomApiV1RoomsRoomIdJoinPostError,
  JoinRoomApiV1RoomsRoomIdJoinPostResponse,
  KickUserApiV1RoomsCurrentUsersUserIdKickPostData,
  KickUserApiV1RoomsCurrentUsersUserIdKickPostError,
  KickUserApiV1RoomsCurrentUsersUserIdKickPostResponse,
  LeaveRoomApiV1RoomsCurrentLeavePostData,
  LeaveRoomApiV1RoomsCurrentLeavePostResponse,
  LogoutApiV1AuthLogoutPostData,
  LogoutApiV1AuthLogoutPostResponse,
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData,
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostError,
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponse,
  RoomStateSseRtV1SseRoomsCurrentGetData,
  RoomStateSseRtV1SseRoomsCurrentGetError,
} from "../types.gen";

/**
 * guest_login
 *
 * POST /api/auth/session/guest
 *
 * 의미:
 * - username만으로 임시(게스트) 로그인 세션을 생성/반환한다.
 * - MVP 단계에서는 JWT 쿠키 발급 및 leave_room 부수 효과는 구현하지 않는다(스텁).
 *
 * 응답:
 * - 200: GuestLoginResponse 반환
 * - 400: 입력/검증 오류 (TBD)
 */
export const guestLoginApiV1AuthGuestLoginPostMutation = (
  options?: Partial<Options<GuestLoginApiV1AuthGuestLoginPostData>>,
): UseMutationOptions<
  GuestLoginApiV1AuthGuestLoginPostResponse,
  AxiosError<GuestLoginApiV1AuthGuestLoginPostError>,
  Options<GuestLoginApiV1AuthGuestLoginPostData>
> => {
  const mutationOptions: UseMutationOptions<
    GuestLoginApiV1AuthGuestLoginPostResponse,
    AxiosError<GuestLoginApiV1AuthGuestLoginPostError>,
    Options<GuestLoginApiV1AuthGuestLoginPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await guestLoginApiV1AuthGuestLoginPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * logout
 *
 * POST /api/auth/session/logout
 *
 * 의미:
 * - 현재 세션 로그아웃을 수행한다.
 * - MVP 단계에서는 쿠키 삭제 및 leave_room 부수 효과는 구현하지 않는다(스텁).
 *
 * 응답:
 * - 200: GuestLogoutResponse 반환
 * - 400: 요청/검증 오류 (TBD)
 */
export const logoutApiV1AuthLogoutPostMutation = (
  options?: Partial<Options<LogoutApiV1AuthLogoutPostData>>,
): UseMutationOptions<
  LogoutApiV1AuthLogoutPostResponse,
  AxiosError<DefaultError>,
  Options<LogoutApiV1AuthLogoutPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LogoutApiV1AuthLogoutPostResponse,
    AxiosError<DefaultError>,
    Options<LogoutApiV1AuthLogoutPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutApiV1AuthLogoutPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * blue_vote
 *
 * POST /api/cases/current/blue-vote
 *
 * 의미:
 * - VOTE phase에서 플레이어가 YES / NO / SKIP 중 하나를 선택한다.
 * - MVP 목업 구현이며, 실제 phase 전환 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 * - VOTE_REJECTED_NO_TOKEN
 */
export const blueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostMutation = (
  options?: Partial<
    Options<BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData>
  >,
): UseMutationOptions<
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponse,
  AxiosError<BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostError>,
  Options<BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData>
> => {
  const mutationOptions: UseMutationOptions<
    BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponse,
    AxiosError<BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostError>,
    Options<BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await blueVoteApiV1CasesCurrentPhasesCurrentBlueVotePost(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        },
      );
      return data;
    },
  };
  return mutationOptions;
};

/**
 * force_skip_discuss
 *
 * POST /api/cases/current/force-skip-discuss
 *
 * 의미:
 * - DISCUSS phase를 강제 종료하고 NIGHT phase로 진행시키는 action을 접수한다.
 * - MVP 단계에서는 권한(Host) 검증을 하지 않으며, 실제 phase 전환 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 */
export const forceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostMutation =
  (
    options?: Partial<
      Options<ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData>
    >,
  ): UseMutationOptions<
    ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponse,
    AxiosError<ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostError>,
    Options<ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponse,
      AxiosError<ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostError>,
      Options<ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await forceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPost(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * init_blue_vote
 *
 * POST /api/cases/current/init-blue-vote
 *
 * 의미:
 * - DISCUSS phase에서 플레이어가 blue-vote의 대상자를 지정하여 VOTE phase 시작을 요청한다.
 * - MVP 목업 구현이며, 실제 phase 검증 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 400: seat_no 범위 오류 (SeatNo)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 404: TARGET_SEAT_EMPTY (대상 seat에 user 없음)
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 * - DISCUSS_REJECTED_NO_TOKEN_INIT
 * - DISCUSS_REJECTED_SELF_VOTE_INIT
 */
export const initBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostMutation =
  (
    options?: Partial<
      Options<InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData>
    >,
  ): UseMutationOptions<
    InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponse,
    AxiosError<InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostError>,
    Options<InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData>
  > => {
    const mutationOptions: UseMutationOptions<
      InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponse,
      AxiosError<InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostError>,
      Options<InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await initBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * red_vote
 *
 * POST /api/cases/current/red-vote
 *
 * 의미:
 * - NIGHT phase에서 red-vote 대상자를 지정하거나(skip 포함) action을 접수한다.
 * - MVP 목업 구현이며, 실제 phase 검증 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 400: seat_no 범위 오류 (SeatNo)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 404: TARGET_SEAT_EMPTY (대상 seat에 user 없음)
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 * - NIGHT_REJECTED_SELF_VOTE (스스로에게 투표 시도)
 */
export const redVoteApiV1CasesCurrentPhasesCurrentRedVotePostMutation = (
  options?: Partial<
    Options<RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData>
  >,
): UseMutationOptions<
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponse,
  AxiosError<RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostError>,
  Options<RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData>
> => {
  const mutationOptions: UseMutationOptions<
    RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponse,
    AxiosError<RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostError>,
    Options<RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await redVoteApiV1CasesCurrentPhasesCurrentRedVotePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * join_room
 *
 * POST /api/rooms/{room_id}/join
 *
 * 의미:
 * - 현재 사용자가 특정 ROOM에 참가를 시도한다.
 * - 성공 시 200 OK + JoinRoomMutation을 반환한다.
 * - 이미 참가 중인 경우에도 200으로 응답하며, changed=False로 표현한다.
 *
 * 비고:
 * - 실제 ROOM_FULL, membership 검증 로직은 추후 구현 예정이다.
 */
export const joinRoomApiV1RoomsRoomIdJoinPostMutation = (
  options?: Partial<Options<JoinRoomApiV1RoomsRoomIdJoinPostData>>,
): UseMutationOptions<
  JoinRoomApiV1RoomsRoomIdJoinPostResponse,
  AxiosError<JoinRoomApiV1RoomsRoomIdJoinPostError>,
  Options<JoinRoomApiV1RoomsRoomIdJoinPostData>
> => {
  const mutationOptions: UseMutationOptions<
    JoinRoomApiV1RoomsRoomIdJoinPostResponse,
    AxiosError<JoinRoomApiV1RoomsRoomIdJoinPostError>,
    Options<JoinRoomApiV1RoomsRoomIdJoinPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await joinRoomApiV1RoomsRoomIdJoinPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * leave_room
 *
 * POST /api/rooms/current/leave
 *
 * 의미:
 * - 현재 사용자가 자신이 속한 ROOM에서 나가기를 시도한다.
 * - 성공 시 200 OK + LeaveRoomMutation을 반환한다.
 * - 이미 방에 속해 있지 않은 경우에도 200으로 응답하며, changed=False로 표현한다.
 */
export const leaveRoomApiV1RoomsCurrentLeavePostMutation = (
  options?: Partial<Options<LeaveRoomApiV1RoomsCurrentLeavePostData>>,
): UseMutationOptions<
  LeaveRoomApiV1RoomsCurrentLeavePostResponse,
  AxiosError<DefaultError>,
  Options<LeaveRoomApiV1RoomsCurrentLeavePostData>
> => {
  const mutationOptions: UseMutationOptions<
    LeaveRoomApiV1RoomsCurrentLeavePostResponse,
    AxiosError<DefaultError>,
    Options<LeaveRoomApiV1RoomsCurrentLeavePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await leaveRoomApiV1RoomsCurrentLeavePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * kick_user
 *
 * POST /api/rooms/current/users/{user_id}/kick
 *
 * 의미:
 * - 특정 USER를 현재 ROOM에서 내보내기를 시도한다.
 * - 성공 시 200 OK + KickUserMutation을 반환한다.
 * - 대상이 해당 ROOM에 없더라도 200으로 응답하며, changed=False로 표현한다.
 *
 * 주의:
 * - 이 API는 대상 room에서의 멤버십 제거 여부만 보장한다.
 */
export const kickUserApiV1RoomsCurrentUsersUserIdKickPostMutation = (
  options?: Partial<Options<KickUserApiV1RoomsCurrentUsersUserIdKickPostData>>,
): UseMutationOptions<
  KickUserApiV1RoomsCurrentUsersUserIdKickPostResponse,
  AxiosError<KickUserApiV1RoomsCurrentUsersUserIdKickPostError>,
  Options<KickUserApiV1RoomsCurrentUsersUserIdKickPostData>
> => {
  const mutationOptions: UseMutationOptions<
    KickUserApiV1RoomsCurrentUsersUserIdKickPostResponse,
    AxiosError<KickUserApiV1RoomsCurrentUsersUserIdKickPostError>,
    Options<KickUserApiV1RoomsCurrentUsersUserIdKickPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await kickUserApiV1RoomsCurrentUsersUserIdKickPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * case_start
 *
 * POST /api/rooms/current/case-start
 *
 * 의미:
 * - 현재 ROOM에서 case 시작을 시도한다.
 * - 성공 시 200 OK + CaseStartMutation을 반환한다.
 * - 권한/조건 불충족 시 403 또는 409로 분리 응답한다.
 *
 * 상태 코드 기준:
 * - 403: room에 속해 있지 않거나 시작 권한이 없는 경우
 * - 409: room 상태가 case 시작 조건을 만족하지 않는 경우
 */
export const caseStartApiV1RoomsCurrentCaseStartPostMutation = (
  options?: Partial<Options<CaseStartApiV1RoomsCurrentCaseStartPostData>>,
): UseMutationOptions<
  CaseStartApiV1RoomsCurrentCaseStartPostResponse,
  AxiosError<CaseStartApiV1RoomsCurrentCaseStartPostError>,
  Options<CaseStartApiV1RoomsCurrentCaseStartPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CaseStartApiV1RoomsCurrentCaseStartPostResponse,
    AxiosError<CaseStartApiV1RoomsCurrentCaseStartPostError>,
    Options<CaseStartApiV1RoomsCurrentCaseStartPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await caseStartApiV1RoomsCurrentCaseStartPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthApiHealthGetQueryKey = (
  options?: Options<HealthApiHealthGetData>,
) => createQueryKey("healthApiHealthGet", options);

/**
 * Health
 */
export const healthApiHealthGetOptions = (
  options?: Options<HealthApiHealthGetData>,
) =>
  queryOptions<
    unknown,
    AxiosError<DefaultError>,
    unknown,
    ReturnType<typeof healthApiHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthApiHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthApiHealthGetQueryKey(options),
  });

export const roomStateSseRtV1SseRoomsCurrentGetQueryKey = (
  options?: Options<RoomStateSseRtV1SseRoomsCurrentGetData>,
) => createQueryKey("roomStateSseRtV1SseRoomsCurrentGet", options);

/**
 * Room State Sse
 *
 * GET /rt/v1/sse/rooms/current
 *
 * Notion: room_state
 * - Auth: User (MVP: X-User-Id 헤더, 추후 JWT로 대체)
 * - Permission: In Room (MVP: X-Room-Id 헤더로 대체)
 *
 * Response (SSE)
 * - event: room_state
 * - id: 단조증가(연결 단위, MVP)
 * - data: RoomStateResponse(JSON)
 *
 * Response (REST)
 * - 403: PERMISSION_DENIED_NOT_IN_ROOM
 */
export const roomStateSseRtV1SseRoomsCurrentGetOptions = (
  options?: Options<RoomStateSseRtV1SseRoomsCurrentGetData>,
) =>
  queryOptions<
    unknown,
    AxiosError<RoomStateSseRtV1SseRoomsCurrentGetError>,
    unknown,
    ReturnType<typeof roomStateSseRtV1SseRoomsCurrentGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await roomStateSseRtV1SseRoomsCurrentGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: roomStateSseRtV1SseRoomsCurrentGetQueryKey(options),
  });
