[pytest]
testpaths = tests
pythonpath = .
markers =
    contract: API contract level tests
    basic: basic features
    api: api level tests
    unit: unit tests
    mvp: only on mvp
asyncio_mode = auto
timeout = 2
timeout_method = thread
