// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData,
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostErrors,
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponses,
  CaseStartApiV1RoomsCurrentCaseStartPostData,
  CaseStartApiV1RoomsCurrentCaseStartPostErrors,
  CaseStartApiV1RoomsCurrentCaseStartPostResponses,
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData,
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostErrors,
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponses,
  GuestLoginApiV1AuthGuestLoginPostData,
  GuestLoginApiV1AuthGuestLoginPostErrors,
  GuestLoginApiV1AuthGuestLoginPostResponses,
  HealthApiHealthGetData,
  HealthApiHealthGetResponses,
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData,
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostErrors,
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponses,
  JoinRoomApiV1RoomsRoomIdJoinPostData,
  JoinRoomApiV1RoomsRoomIdJoinPostErrors,
  JoinRoomApiV1RoomsRoomIdJoinPostResponses,
  KickUserApiV1RoomsCurrentUsersUserIdKickPostData,
  KickUserApiV1RoomsCurrentUsersUserIdKickPostErrors,
  KickUserApiV1RoomsCurrentUsersUserIdKickPostResponses,
  LeaveRoomApiV1RoomsCurrentLeavePostData,
  LeaveRoomApiV1RoomsCurrentLeavePostResponses,
  LogoutApiV1AuthLogoutPostData,
  LogoutApiV1AuthLogoutPostErrors,
  LogoutApiV1AuthLogoutPostResponses,
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData,
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostErrors,
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponses,
  RoomStateSseRtV1SseRoomsCurrentGetData,
  RoomStateSseRtV1SseRoomsCurrentGetErrors,
  RoomStateSseRtV1SseRoomsCurrentGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * guest_login
 *
 * POST /api/auth/session/guest
 *
 * 의미:
 * - username만으로 임시(게스트) 로그인 세션을 생성/반환한다.
 * - MVP 단계에서는 JWT 쿠키 발급 및 leave_room 부수 효과는 구현하지 않는다(스텁).
 *
 * 응답:
 * - 200: GuestLoginResponse 반환
 * - 400: 입력/검증 오류 (TBD)
 */
export const guestLoginApiV1AuthGuestLoginPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GuestLoginApiV1AuthGuestLoginPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GuestLoginApiV1AuthGuestLoginPostResponses,
    GuestLoginApiV1AuthGuestLoginPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/guest-login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * logout
 *
 * POST /api/auth/session/logout
 *
 * 의미:
 * - 현재 세션 로그아웃을 수행한다.
 * - MVP 단계에서는 쿠키 삭제 및 leave_room 부수 효과는 구현하지 않는다(스텁).
 *
 * 응답:
 * - 200: GuestLogoutResponse 반환
 * - 400: 요청/검증 오류 (TBD)
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    LogoutApiV1AuthLogoutPostResponses,
    LogoutApiV1AuthLogoutPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/logout",
    ...options,
  });

/**
 * blue_vote
 *
 * POST /api/cases/current/blue-vote
 *
 * 의미:
 * - VOTE phase에서 플레이어가 YES / NO / SKIP 중 하나를 선택한다.
 * - MVP 목업 구현이며, 실제 phase 전환 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 * - VOTE_REJECTED_NO_TOKEN
 */
export const blueVoteApiV1CasesCurrentPhasesCurrentBlueVotePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponses,
    BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/cases/current/phases/current/blue-vote",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * force_skip_discuss
 *
 * POST /api/cases/current/force-skip-discuss
 *
 * 의미:
 * - DISCUSS phase를 강제 종료하고 NIGHT phase로 진행시키는 action을 접수한다.
 * - MVP 단계에서는 권한(Host) 검증을 하지 않으며, 실제 phase 전환 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 */
export const forceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPost =
  <ThrowOnError extends boolean = false>(
    options?: Options<
      ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData,
      ThrowOnError
    >,
  ) =>
    (options?.client ?? client).post<
      ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponses,
      ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/cases/current/phases/current/force-skip-discuss",
      ...options,
    });

/**
 * init_blue_vote
 *
 * POST /api/cases/current/init-blue-vote
 *
 * 의미:
 * - DISCUSS phase에서 플레이어가 blue-vote의 대상자를 지정하여 VOTE phase 시작을 요청한다.
 * - MVP 목업 구현이며, 실제 phase 검증 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 400: seat_no 범위 오류 (SeatNo)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 404: TARGET_SEAT_EMPTY (대상 seat에 user 없음)
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 * - DISCUSS_REJECTED_NO_TOKEN_INIT
 * - DISCUSS_REJECTED_SELF_VOTE_INIT
 */
export const initBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponses,
    InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/cases/current/phases/current/init-blue-vote",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * red_vote
 *
 * POST /api/cases/current/red-vote
 *
 * 의미:
 * - NIGHT phase에서 red-vote 대상자를 지정하거나(skip 포함) action을 접수한다.
 * - MVP 목업 구현이며, 실제 phase 검증 및 SSE emit은 추후 구현한다.
 *
 * 응답:
 * - 200: action 접수 성공 (ActionReceipt)
 * - 400: seat_no 범위 오류 (SeatNo)
 * - 403: room/case 컨텍스트 없음
 * - PERMISSION_DENIED_NOT_IN_ROOM
 * - PERMISSION_DENIED_NOT_IN_CASE
 * - 404: TARGET_SEAT_EMPTY (대상 seat에 user 없음)
 * - 409: 동일 phase 컨텍스트에서 상태 충돌
 * - PHASE_REJECTED_ALREADY_DECIDED
 * - PHASE_REJECTED_CONFLICT_ACTION
 * - NIGHT_REJECTED_SELF_VOTE (스스로에게 투표 시도)
 */
export const redVoteApiV1CasesCurrentPhasesCurrentRedVotePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponses,
    RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/cases/current/phases/current/red-vote",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * join_room
 *
 * POST /api/rooms/{room_id}/join
 *
 * 의미:
 * - 현재 사용자가 특정 ROOM에 참가를 시도한다.
 * - 성공 시 200 OK + JoinRoomMutation을 반환한다.
 * - 이미 참가 중인 경우에도 200으로 응답하며, changed=False로 표현한다.
 *
 * 비고:
 * - 실제 ROOM_FULL, membership 검증 로직은 추후 구현 예정이다.
 */
export const joinRoomApiV1RoomsRoomIdJoinPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<JoinRoomApiV1RoomsRoomIdJoinPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    JoinRoomApiV1RoomsRoomIdJoinPostResponses,
    JoinRoomApiV1RoomsRoomIdJoinPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/rooms/{room_id}/join",
    ...options,
  });

/**
 * leave_room
 *
 * POST /api/rooms/current/leave
 *
 * 의미:
 * - 현재 사용자가 자신이 속한 ROOM에서 나가기를 시도한다.
 * - 성공 시 200 OK + LeaveRoomMutation을 반환한다.
 * - 이미 방에 속해 있지 않은 경우에도 200으로 응답하며, changed=False로 표현한다.
 */
export const leaveRoomApiV1RoomsCurrentLeavePost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LeaveRoomApiV1RoomsCurrentLeavePostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    LeaveRoomApiV1RoomsCurrentLeavePostResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/rooms/current/leave",
    ...options,
  });

/**
 * kick_user
 *
 * POST /api/rooms/current/users/{user_id}/kick
 *
 * 의미:
 * - 특정 USER를 현재 ROOM에서 내보내기를 시도한다.
 * - 성공 시 200 OK + KickUserMutation을 반환한다.
 * - 대상이 해당 ROOM에 없더라도 200으로 응답하며, changed=False로 표현한다.
 *
 * 주의:
 * - 이 API는 대상 room에서의 멤버십 제거 여부만 보장한다.
 */
export const kickUserApiV1RoomsCurrentUsersUserIdKickPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    KickUserApiV1RoomsCurrentUsersUserIdKickPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    KickUserApiV1RoomsCurrentUsersUserIdKickPostResponses,
    KickUserApiV1RoomsCurrentUsersUserIdKickPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/rooms/current/users/{user_id}/kick",
    ...options,
  });

/**
 * case_start
 *
 * POST /api/rooms/current/case-start
 *
 * 의미:
 * - 현재 ROOM에서 case 시작을 시도한다.
 * - 성공 시 200 OK + CaseStartMutation을 반환한다.
 * - 권한/조건 불충족 시 403 또는 409로 분리 응답한다.
 *
 * 상태 코드 기준:
 * - 403: room에 속해 있지 않거나 시작 권한이 없는 경우
 * - 409: room 상태가 case 시작 조건을 만족하지 않는 경우
 */
export const caseStartApiV1RoomsCurrentCaseStartPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CaseStartApiV1RoomsCurrentCaseStartPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CaseStartApiV1RoomsCurrentCaseStartPostResponses,
    CaseStartApiV1RoomsCurrentCaseStartPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/rooms/current/case-start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthApiHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthApiHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health",
    ...options,
  });

/**
 * Room State Sse
 *
 * GET /rt/v1/sse/rooms/current
 *
 * Notion: room_state
 * - Auth: User (MVP: X-User-Id 헤더, 추후 JWT로 대체)
 * - Permission: In Room (MVP: X-Room-Id 헤더로 대체)
 *
 * Response (SSE)
 * - event: room_state
 * - id: 단조증가(연결 단위, MVP)
 * - data: RoomStateResponse(JSON)
 *
 * Response (REST)
 * - 403: PERMISSION_DENIED_NOT_IN_ROOM
 */
export const roomStateSseRtV1SseRoomsCurrentGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RoomStateSseRtV1SseRoomsCurrentGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    RoomStateSseRtV1SseRoomsCurrentGetResponses,
    RoomStateSseRtV1SseRoomsCurrentGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/rt/v1/sse/rooms/current",
    ...options,
  });
