// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:8000" | (string & {});
};

/**
 * ActionConflictCode
 *
 * Action API 공통 409 코드.
 *
 * 의미:
 * - 동일한 room/case/phase 컨텍스트 안에서 상태와 충돌하는 action을 시도한 경우에 사용한다.
 */
export type ActionConflictCode =
  | "PHASE_REJECTED_ALREADY_DECIDED"
  | "PHASE_REJECTED_CONFLICT_ACTION";

/**
 * ActionForbiddenCode
 *
 * Action API 공통 403 코드.
 *
 * 의미:
 * - room/case 컨텍스트 자체가 없는 상태에서 action을 시도한 경우에 사용한다.
 */
export type ActionForbiddenCode =
  | "PERMISSION_DENIED_NOT_IN_ROOM"
  | "PERMISSION_DENIED_NOT_IN_CASE";

/**
 * ActionReceipt
 *
 * 공통 Action Receipt.
 *
 * 의미:
 * - Action API가 서버에 의해 "접수(accepted)" 되었음을 나타낸다.
 * - 실제 상태 변화(스냅샷)는 SSE(case_state)로 확인한다.
 *
 * 필드 해석:
 * - action_id: 동일 case 내에서 단조 증가하는 action 식별자(1..)
 * - phase_id: action이 접수된 시점의 phase 식별자(UUID)
 * - accepted_at: 서버가 action을 접수한 시각(UTC, ISO 8601)
 */
export type ActionReceipt = {
  /**
   * Action Id
   *
   * Action id (1..).
   */
  action_id: number;
  /**
   * Phase Id
   *
   * Phase id (uuid).
   */
  phase_id: string;
  /**
   * Accepted At
   *
   * Accepted at (UTC).
   */
  accepted_at: string;
};

/**
 * BlueVoteChoice
 */
export type BlueVoteChoice = "YES" | "NO" | "SKIP";

/**
 * BlueVoteConflictCode
 */
export type BlueVoteConflictCode = "VOTE_REJECTED_NO_TOKEN";

/**
 * BlueVoteRequest
 *
 * POST /api/cases/current/blue-vote 요청 바디.
 *
 * 의미:
 * - VOTE phase에서 현재 target에 대해 YES / NO / SKIP 중 하나를 선택한다.
 */
export type BlueVoteRequest = {
  /**
   * Vote choice in VOTE phase.
   */
  choice: BlueVoteChoice;
};

/**
 * BlueVoteSuccessCode
 */
export type BlueVoteSuccessCode = "OK";

/**
 * CaseStartConflictCode
 */
export type CaseStartConflictCode =
  | "ROOM_CASE_RUNNING"
  | "ROOM_NOT_ENOUGH_PLAYERS"
  | "ROOM_NOT_ALL_READY"
  | "ROOM_DELETED";

/**
 * CaseStartForbiddenCode
 */
export type CaseStartForbiddenCode =
  | "PERMISSION_DENIED_NOT_IN_ROOM"
  | "PERMISSION_DENIED_NOT_HOST";

/**
 * CaseStartMutation
 *
 * POST /api/rooms/current/case-start 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 현재 사용자가 ROOM에서 case 시작을 시도한 "성공 결과"를 나타낸다.
 * - 권한/조건 불충족으로 시작에 실패한 경우는 403/409로 분리되며, body의 data는 null이다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == ME
 * - subject_id == None
 * - on_target == True (요청 이후 room에 case가 존재)
 * - changed == True (요청으로 인해 실제로 case 시작이 발생)
 * - reason == STARTED
 */
export type CaseStartMutation = {
  target?: Target;
  subject?: Subject;
  /**
   * Subject Id
   *
   * Always null for subject=ME.
   */
  subject_id?: null;
  /**
   * On Target
   *
   * Always true for case_start success mutation.
   */
  on_target?: true;
  /**
   * Changed
   *
   * Always true for case_start success mutation.
   */
  changed?: true;
  /**
   * Reason string ("STARTED").
   */
  reason?: CaseStartReason;
};

/**
 * CaseStartReason
 */
export type CaseStartReason = "STARTED";

/**
 * CaseStartRequest
 */
export type CaseStartRequest = {
  /**
   * Red Player Count
   */
  red_player_count?: number | null;
};

/**
 * CaseStartSuccessCode
 */
export type CaseStartSuccessCode = "OK";

/**
 * CommonErrorCode
 */
export type CommonErrorCode = "VALIDATION_ERROR";

/**
 * Envelope[ActionReceipt, BlueVoteSuccessCode]
 */
export type EnvelopeActionReceiptBlueVoteSuccessCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: BlueVoteSuccessCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: ActionReceipt | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[ActionReceipt, ForceSkipDiscussSuccessCode]
 */
export type EnvelopeActionReceiptForceSkipDiscussSuccessCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: ForceSkipDiscussSuccessCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: ActionReceipt | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[ActionReceipt, InitBlueVoteSuccessCode]
 */
export type EnvelopeActionReceiptInitBlueVoteSuccessCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: InitBlueVoteSuccessCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: ActionReceipt | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[ActionReceipt, RedVoteSuccessCode]
 */
export type EnvelopeActionReceiptRedVoteSuccessCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: RedVoteSuccessCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: ActionReceipt | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[CaseStartMutation, CaseStartSuccessCode]
 */
export type EnvelopeCaseStartMutationCaseStartSuccessCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: CaseStartSuccessCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: CaseStartMutation | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[GuestLoginData, LoginCode]
 */
export type EnvelopeGuestLoginDataLoginCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: LoginCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: GuestLoginData | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[JoinRoomMutation, JoinRoomCode]
 */
export type EnvelopeJoinRoomMutationJoinRoomCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: JoinRoomCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: JoinRoomMutation | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[KickUserMutation, KickUserCode]
 */
export type EnvelopeKickUserMutationKickUserCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: KickUserCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: KickUserMutation | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[LeaveRoomMutation, LeaveRoomCode]
 */
export type EnvelopeLeaveRoomMutationLeaveRoomCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: LeaveRoomCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Actual json payload of responses.
   */
  data?: LeaveRoomMutation | null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, ActionConflictCode]
 */
export type EnvelopeNoneTypeActionConflictCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: ActionConflictCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, ActionForbiddenCode]
 */
export type EnvelopeNoneTypeActionForbiddenCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: ActionForbiddenCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, CaseStartConflictCode]
 */
export type EnvelopeNoneTypeCaseStartConflictCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: CaseStartConflictCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, CaseStartForbiddenCode]
 */
export type EnvelopeNoneTypeCaseStartForbiddenCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: CaseStartForbiddenCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, CommonErrorCode]
 */
export type EnvelopeNoneTypeCommonErrorCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: CommonErrorCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, InitBlueVoteBadRequestCode]
 */
export type EnvelopeNoneTypeInitBlueVoteBadRequestCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: InitBlueVoteBadRequestCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, InitBlueVoteNotFoundCode]
 */
export type EnvelopeNoneTypeInitBlueVoteNotFoundCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: InitBlueVoteNotFoundCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, LogoutCode]
 */
export type EnvelopeNoneTypeLogoutCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: LogoutCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, RedVoteBadRequestCode]
 */
export type EnvelopeNoneTypeRedVoteBadRequestCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: RedVoteBadRequestCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, RedVoteNotFoundCode]
 */
export type EnvelopeNoneTypeRedVoteNotFoundCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Domain result code or snapshot trigger code.
   */
  code: RedVoteNotFoundCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, Union[ActionConflictCode, BlueVoteConflictCode]]
 */
export type EnvelopeNoneTypeUnionActionConflictCodeBlueVoteConflictCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Code
   *
   * Domain result code or snapshot trigger code.
   */
  code: ActionConflictCode | BlueVoteConflictCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, Union[ActionConflictCode, InitBlueVoteConflictCode]]
 */
export type EnvelopeNoneTypeUnionActionConflictCodeInitBlueVoteConflictCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Code
   *
   * Domain result code or snapshot trigger code.
   */
  code: ActionConflictCode | InitBlueVoteConflictCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Envelope[NoneType, Union[ActionConflictCode, RedVoteConflictCode]]
 */
export type EnvelopeNoneTypeUnionActionConflictCodeRedVoteConflictCode = {
  /**
   * Ok
   *
   * Domain-level success/failure.
   */
  ok: boolean;
  /**
   * Code
   *
   * Domain result code or snapshot trigger code.
   */
  code: ActionConflictCode | RedVoteConflictCode;
  /**
   * Message
   *
   * Human-friendly optional message.
   */
  message?: string | null;
  /**
   * Data
   *
   * Actual json payload of responses.
   */
  data?: null;
  /**
   * Meta
   *
   * Optional metadata.
   */
  meta?: {
    [key: string]: unknown;
  } | null;
};

/**
 * ForceSkipDiscussSuccessCode
 */
export type ForceSkipDiscussSuccessCode = "OK";

/**
 * GuestLoginData
 *
 * If in_case is true, current_case_id must be provided; otherwise it must be null.
 */
export type GuestLoginData = {
  /**
   * Id
   *
   * User ID (UUID)
   */
  id: string;
  /**
   * Username
   *
   * Username
   */
  username: string;
  /**
   * In Case
   *
   * Whether the user is currently in a case
   */
  in_case: boolean;
  /**
   * Current Case Id
   *
   * Current case id if in_case is true
   */
  current_case_id?: string | null;
};

/**
 * GuestLoginRequest
 */
export type GuestLoginRequest = {
  /**
   * Username
   *
   * Guest username (3..32)
   */
  username: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InitBlueVoteBadRequestCode
 */
export type InitBlueVoteBadRequestCode = "INVALID_TARGET_SEAT_NO";

/**
 * InitBlueVoteConflictCode
 */
export type InitBlueVoteConflictCode =
  | "DISCUSS_REJECTED_NO_TOKEN_INIT"
  | "DISCUSS_REJECTED_SELF_VOTE_INIT";

/**
 * InitBlueVoteNotFoundCode
 */
export type InitBlueVoteNotFoundCode = "TARGET_SEAT_EMPTY";

/**
 * InitBlueVoteRequest
 *
 * POST /api/cases/current/init-blue-vote 요청 바디.
 *
 * 의미:
 * - DISCUSS phase에서 blue-vote의 대상 seat_no를 지정하여 VOTE phase 시작을 요청한다.
 *
 * 필드 해석:
 * - target_seat_no: 유효한 seat_no(SeatNo)
 */
export type InitBlueVoteRequest = {
  /**
   * Target Seat No
   *
   * Target seat no.
   */
  target_seat_no: number;
};

/**
 * InitBlueVoteSuccessCode
 */
export type InitBlueVoteSuccessCode = "OK";

/**
 * JoinRoomCode
 */
export type JoinRoomCode = "OK";

/**
 * JoinRoomMutation
 *
 * POST /api/rooms/{room_id}/join 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 현재 사용자가 특정 ROOM에 참가를 시도한 결과를 나타낸다.
 * - 이미 참가 중인 경우에도 200으로 응답하며, changed=False로 표현한다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == ME
 * - subject_id == None
 * - on_target == True (요청 이후 항상 방에 속한 상태)
 * - changed: 실제로 참가 상태가 변경되었는지 여부
 * - reason: JOINED | ALREADY_JOINED
 */
export type JoinRoomMutation = {
  target?: Target;
  subject?: Subject;
  /**
   * Subject Id
   *
   * Always null for subject=ME.
   */
  subject_id?: null;
  /**
   * On Target
   *
   * Always true for join_room mutation.
   */
  on_target?: true;
  /**
   * Changed
   *
   * Whether the room membership actually changed by this request.
   */
  changed: boolean;
  /**
   * Reason string ("JOINED" | "ALREADY_JOINED").
   */
  reason: JoinRoomReason;
};

/**
 * JoinRoomReason
 */
export type JoinRoomReason = "JOINED" | "ALREADY_JOINED";

/**
 * KickUserCode
 */
export type KickUserCode = "OK";

/**
 * KickUserMutation
 *
 * POST /api/rooms/current/users/{user_id}/kick 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 특정 USER를 현재 ROOM에서 내보내기를 시도한 결과를 나타낸다.
 * - 대상이 해당 ROOM에 없더라도 200으로 응답하며, changed=False로 표현한다.
 * - 이 mutation은 대상 room에서 실제 멤버십이 제거되었는지만 보장한다.
 * 대상 유저의 다른 room 소속 여부는 반환하지 않는다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == USER
 * - subject_id: 대상 USER의 식별자(UUID)
 * - on_target == False (요청 이후 대상은 해당 ROOM에 속하지 않음)
 * - changed: 실제로 멤버십이 제거되었는지 여부
 * - reason: KICKED | NOT_IN_ROOM
 */
export type KickUserMutation = {
  target?: Target;
  subject?: Subject;
  /**
   * Subject Id
   *
   * Target user's id.
   */
  subject_id: string;
  /**
   * On Target
   *
   * Always false for kick_user mutation.
   */
  on_target?: false;
  /**
   * Changed
   *
   * Whether the room membership actually changed by this request.
   */
  changed: boolean;
  /**
   * Reason string ("KICKED" | "NOT_IN_ROOM").
   */
  reason: KickUserReason;
};

/**
 * KickUserReason
 */
export type KickUserReason = "KICKED" | "NOT_IN_ROOM";

/**
 * LeaveRoomCode
 */
export type LeaveRoomCode = "OK";

/**
 * LeaveRoomMutation
 *
 * POST /api/rooms/current/leave 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 현재 사용자가 ROOM에서 나가기를 시도한 결과를 나타낸다.
 * - 이미 방에 속해 있지 않은 경우에도 200으로 응답하며, changed=False로 표현한다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == ME
 * - subject_id == None
 * - on_target == False (요청 이후 항상 방에 속하지 않은 상태)
 * - changed: 실제로 멤버십이 변경되었는지 여부
 * - reason: LEFT | ALREADY_LEFT
 */
export type LeaveRoomMutation = {
  target?: Target;
  subject?: Subject;
  /**
   * Subject Id
   *
   * Always null for subject=ME.
   */
  subject_id?: null;
  /**
   * On Target
   *
   * Always false for leave_room mutation.
   */
  on_target?: false;
  /**
   * Changed
   *
   * Whether the room membership actually changed by this request.
   */
  changed: boolean;
  /**
   * Reason string ("LEFT" | "ALREADY_LEFT").
   */
  reason: LeaveRoomReason;
};

/**
 * LeaveRoomReason
 */
export type LeaveRoomReason = "LEFT" | "ALREADY_LEFT";

/**
 * LoginCode
 */
export type LoginCode = "OK";

/**
 * LogoutCode
 */
export type LogoutCode = "OK";

/**
 * RedVoteBadRequestCode
 */
export type RedVoteBadRequestCode = "INVALID_TARGET_SEAT_NO";

/**
 * RedVoteConflictCode
 */
export type RedVoteConflictCode = "NIGHT_REJECTED_SELF_VOTE";

/**
 * RedVoteNotFoundCode
 */
export type RedVoteNotFoundCode = "TARGET_SEAT_EMPTY";

/**
 * RedVoteRequest
 *
 * POST /api/cases/current/red-vote 요청 바디.
 *
 * 의미:
 * - NIGHT phase에서 red-vote 대상 seat_no를 지정한다.
 * - skip인 경우 target_seat_no를 null로 전송한다.
 *
 * 필드 해석:
 * - target_seat_no: 유효한 seat_no(SeatNo), 또는 skip(null)
 */
export type RedVoteRequest = {
  /**
   * Target Seat No
   *
   * Target seat no. null means skip.
   */
  target_seat_no?: number | null;
};

/**
 * RedVoteSuccessCode
 */
export type RedVoteSuccessCode = "OK";

/**
 * Subject
 */
export type Subject = "ME" | "USER";

/**
 * Target
 */
export type Target = "ROOM" | "CASE";

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GuestLoginApiV1AuthGuestLoginPostData = {
  body: GuestLoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/guest-login";
};

export type GuestLoginApiV1AuthGuestLoginPostErrors = {
  /**
   * TBD: Bad Request
   */
  400: unknown;
  /**
   * Unprocessable Entity
   */
  422: EnvelopeNoneTypeCommonErrorCode;
};

export type GuestLoginApiV1AuthGuestLoginPostError =
  GuestLoginApiV1AuthGuestLoginPostErrors[keyof GuestLoginApiV1AuthGuestLoginPostErrors];

export type GuestLoginApiV1AuthGuestLoginPostResponses = {
  /**
   * Temporary API. Creates/returns a guest user session. (MVP stub: no JWT cookies are issued yet, and no leave_room side-effect is triggered.)
   */
  200: EnvelopeGuestLoginDataLoginCode;
};

export type GuestLoginApiV1AuthGuestLoginPostResponse =
  GuestLoginApiV1AuthGuestLoginPostResponses[keyof GuestLoginApiV1AuthGuestLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type LogoutApiV1AuthLogoutPostErrors = {
  /**
   * TBD: Bad Request
   */
  400: unknown;
};

export type LogoutApiV1AuthLogoutPostResponses = {
  /**
   * Temporary API. Logs out the current session. (MVP stub: does not clear cookies yet, and no leave_room side-effect is triggered.)
   */
  200: EnvelopeNoneTypeLogoutCode;
};

export type LogoutApiV1AuthLogoutPostResponse =
  LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData = {
  body: BlueVoteRequest;
  path?: never;
  query?: never;
  url: "/api/v1/cases/current/phases/current/blue-vote";
};

export type BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostErrors = {
  /**
   * Forbidden
   */
  403: EnvelopeNoneTypeActionForbiddenCode;
  /**
   * Conflict
   */
  409: EnvelopeNoneTypeUnionActionConflictCodeBlueVoteConflictCode;
  /**
   * Unprocessable Entity
   */
  422: EnvelopeNoneTypeCommonErrorCode;
};

export type BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostError =
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostErrors[keyof BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostErrors];

export type BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponses = {
  /**
   * Response Blue Vote Api V1 Cases Current Phases Current Blue Vote Post
   *
   * Successful Response
   */
  200:
    | EnvelopeActionReceiptBlueVoteSuccessCode
    | EnvelopeNoneTypeUnionActionConflictCodeBlueVoteConflictCode
    | EnvelopeNoneTypeActionForbiddenCode;
};

export type BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponse =
  BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponses[keyof BlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponses];

export type ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData =
  {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/cases/current/phases/current/force-skip-discuss";
  };

export type ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostErrors =
  {
    /**
     * Forbidden
     */
    403: EnvelopeNoneTypeActionForbiddenCode;
    /**
     * Conflict
     */
    409: EnvelopeNoneTypeActionConflictCode;
  };

export type ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostError =
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostErrors[keyof ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostErrors];

export type ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponses =
  {
    /**
     * Response Force Skip Discuss Api V1 Cases Current Phases Current Force Skip Discuss Post
     *
     * Successful Response
     */
    200:
      | EnvelopeActionReceiptForceSkipDiscussSuccessCode
      | EnvelopeNoneTypeActionConflictCode
      | EnvelopeNoneTypeActionForbiddenCode;
  };

export type ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponse =
  ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponses[keyof ForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponses];

export type InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData = {
  body: InitBlueVoteRequest;
  path?: never;
  query?: never;
  url: "/api/v1/cases/current/phases/current/init-blue-vote";
};

export type InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostErrors = {
  /**
   * Bad Request
   */
  400: EnvelopeNoneTypeInitBlueVoteBadRequestCode;
  /**
   * Forbidden
   */
  403: EnvelopeNoneTypeActionForbiddenCode;
  /**
   * Not Found
   */
  404: EnvelopeNoneTypeInitBlueVoteNotFoundCode;
  /**
   * Conflict
   */
  409: EnvelopeNoneTypeUnionActionConflictCodeInitBlueVoteConflictCode;
  /**
   * Unprocessable Entity
   */
  422: EnvelopeNoneTypeCommonErrorCode;
};

export type InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostError =
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostErrors[keyof InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostErrors];

export type InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponses =
  {
    /**
     * Response Init Blue Vote Api V1 Cases Current Phases Current Init Blue Vote Post
     *
     * Successful Response
     */
    200:
      | EnvelopeActionReceiptInitBlueVoteSuccessCode
      | EnvelopeNoneTypeInitBlueVoteBadRequestCode
      | EnvelopeNoneTypeUnionActionConflictCodeInitBlueVoteConflictCode
      | EnvelopeNoneTypeInitBlueVoteNotFoundCode
      | EnvelopeNoneTypeActionForbiddenCode;
  };

export type InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponse =
  InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponses[keyof InitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponses];

export type RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData = {
  body: RedVoteRequest;
  path?: never;
  query?: never;
  url: "/api/v1/cases/current/phases/current/red-vote";
};

export type RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostErrors = {
  /**
   * Bad Request
   */
  400: EnvelopeNoneTypeRedVoteBadRequestCode;
  /**
   * Forbidden
   */
  403: EnvelopeNoneTypeActionForbiddenCode;
  /**
   * Not Found
   */
  404: EnvelopeNoneTypeRedVoteNotFoundCode;
  /**
   * Conflict
   */
  409: EnvelopeNoneTypeUnionActionConflictCodeRedVoteConflictCode;
  /**
   * Unprocessable Entity
   */
  422: EnvelopeNoneTypeCommonErrorCode;
};

export type RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostError =
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostErrors[keyof RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostErrors];

export type RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponses = {
  /**
   * Response Red Vote Api V1 Cases Current Phases Current Red Vote Post
   *
   * Successful Response
   */
  200:
    | EnvelopeActionReceiptRedVoteSuccessCode
    | EnvelopeNoneTypeRedVoteBadRequestCode
    | EnvelopeNoneTypeRedVoteNotFoundCode
    | EnvelopeNoneTypeActionForbiddenCode
    | EnvelopeNoneTypeUnionActionConflictCodeRedVoteConflictCode;
};

export type RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponse =
  RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponses[keyof RedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponses];

export type JoinRoomApiV1RoomsRoomIdJoinPostData = {
  body?: never;
  path: {
    /**
     * Room Id
     *
     * Room identifier (UUID)
     */
    room_id: string;
  };
  query?: never;
  url: "/api/v1/rooms/{room_id}/join";
};

export type JoinRoomApiV1RoomsRoomIdJoinPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type JoinRoomApiV1RoomsRoomIdJoinPostError =
  JoinRoomApiV1RoomsRoomIdJoinPostErrors[keyof JoinRoomApiV1RoomsRoomIdJoinPostErrors];

export type JoinRoomApiV1RoomsRoomIdJoinPostResponses = {
  /**
   * Successful Response
   */
  200: EnvelopeJoinRoomMutationJoinRoomCode;
};

export type JoinRoomApiV1RoomsRoomIdJoinPostResponse =
  JoinRoomApiV1RoomsRoomIdJoinPostResponses[keyof JoinRoomApiV1RoomsRoomIdJoinPostResponses];

export type LeaveRoomApiV1RoomsCurrentLeavePostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/rooms/current/leave";
};

export type LeaveRoomApiV1RoomsCurrentLeavePostResponses = {
  /**
   * Successful Response
   */
  200: EnvelopeLeaveRoomMutationLeaveRoomCode;
};

export type LeaveRoomApiV1RoomsCurrentLeavePostResponse =
  LeaveRoomApiV1RoomsCurrentLeavePostResponses[keyof LeaveRoomApiV1RoomsCurrentLeavePostResponses];

export type KickUserApiV1RoomsCurrentUsersUserIdKickPostData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/rooms/current/users/{user_id}/kick";
};

export type KickUserApiV1RoomsCurrentUsersUserIdKickPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type KickUserApiV1RoomsCurrentUsersUserIdKickPostError =
  KickUserApiV1RoomsCurrentUsersUserIdKickPostErrors[keyof KickUserApiV1RoomsCurrentUsersUserIdKickPostErrors];

export type KickUserApiV1RoomsCurrentUsersUserIdKickPostResponses = {
  /**
   * Successful Response
   */
  200: EnvelopeKickUserMutationKickUserCode;
};

export type KickUserApiV1RoomsCurrentUsersUserIdKickPostResponse =
  KickUserApiV1RoomsCurrentUsersUserIdKickPostResponses[keyof KickUserApiV1RoomsCurrentUsersUserIdKickPostResponses];

export type CaseStartApiV1RoomsCurrentCaseStartPostData = {
  body: CaseStartRequest;
  path?: never;
  query?: never;
  url: "/api/v1/rooms/current/case-start";
};

export type CaseStartApiV1RoomsCurrentCaseStartPostErrors = {
  /**
   * Forbidden
   */
  403: EnvelopeNoneTypeCaseStartForbiddenCode;
  /**
   * Conflict
   */
  409: EnvelopeNoneTypeCaseStartConflictCode;
  /**
   * Unprocessable Entity
   */
  422: EnvelopeNoneTypeCommonErrorCode;
};

export type CaseStartApiV1RoomsCurrentCaseStartPostError =
  CaseStartApiV1RoomsCurrentCaseStartPostErrors[keyof CaseStartApiV1RoomsCurrentCaseStartPostErrors];

export type CaseStartApiV1RoomsCurrentCaseStartPostResponses = {
  /**
   * Successful Response
   */
  200: EnvelopeCaseStartMutationCaseStartSuccessCode;
};

export type CaseStartApiV1RoomsCurrentCaseStartPostResponse =
  CaseStartApiV1RoomsCurrentCaseStartPostResponses[keyof CaseStartApiV1RoomsCurrentCaseStartPostResponses];

export type HealthApiHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type HealthApiHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RoomStateSseRtV1SseRoomsCurrentGetData = {
  body?: never;
  headers?: {
    /**
     * X-User-Id
     */
    "X-User-Id"?: string | null;
    /**
     * X-Room-Id
     */
    "X-Room-Id"?: string | null;
  };
  path?: never;
  query?: never;
  url: "/rt/v1/sse/rooms/current";
};

export type RoomStateSseRtV1SseRoomsCurrentGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RoomStateSseRtV1SseRoomsCurrentGetError =
  RoomStateSseRtV1SseRoomsCurrentGetErrors[keyof RoomStateSseRtV1SseRoomsCurrentGetErrors];

export type RoomStateSseRtV1SseRoomsCurrentGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
