// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * ActionConflictCode
 *
 * Action API 공통 409 코드.
 *
 * 의미:
 * - 동일한 room/case/phase 컨텍스트 안에서 상태와 충돌하는 action을 시도한 경우에 사용한다.
 */
export const zActionConflictCode = z.enum([
  "PHASE_REJECTED_ALREADY_DECIDED",
  "PHASE_REJECTED_CONFLICT_ACTION",
]);

/**
 * ActionForbiddenCode
 *
 * Action API 공통 403 코드.
 *
 * 의미:
 * - room/case 컨텍스트 자체가 없는 상태에서 action을 시도한 경우에 사용한다.
 */
export const zActionForbiddenCode = z.enum([
  "PERMISSION_DENIED_NOT_IN_ROOM",
  "PERMISSION_DENIED_NOT_IN_CASE",
]);

/**
 * ActionReceipt
 *
 * 공통 Action Receipt.
 *
 * 의미:
 * - Action API가 서버에 의해 "접수(accepted)" 되었음을 나타낸다.
 * - 실제 상태 변화(스냅샷)는 SSE(case_state)로 확인한다.
 *
 * 필드 해석:
 * - action_id: 동일 case 내에서 단조 증가하는 action 식별자(1..)
 * - phase_id: action이 접수된 시점의 phase 식별자(UUID)
 * - accepted_at: 서버가 action을 접수한 시각(UTC, ISO 8601)
 */
export const zActionReceipt = z.object({
  action_id: z.int().gte(1),
  phase_id: z.uuid(),
  accepted_at: z.iso.datetime(),
});

/**
 * BlueVoteChoice
 */
export const zBlueVoteChoice = z.enum(["YES", "NO", "SKIP"]);

/**
 * BlueVoteConflictCode
 */
export const zBlueVoteConflictCode = z.enum(["VOTE_REJECTED_NO_TOKEN"]);

/**
 * BlueVoteRequest
 *
 * POST /api/cases/current/blue-vote 요청 바디.
 *
 * 의미:
 * - VOTE phase에서 현재 target에 대해 YES / NO / SKIP 중 하나를 선택한다.
 */
export const zBlueVoteRequest = z.object({
  choice: zBlueVoteChoice,
});

/**
 * BlueVoteSuccessCode
 */
export const zBlueVoteSuccessCode = z.enum(["OK"]);

/**
 * CaseStartConflictCode
 */
export const zCaseStartConflictCode = z.enum([
  "ROOM_CASE_RUNNING",
  "ROOM_NOT_ENOUGH_PLAYERS",
  "ROOM_NOT_ALL_READY",
  "ROOM_DELETED",
]);

/**
 * CaseStartForbiddenCode
 */
export const zCaseStartForbiddenCode = z.enum([
  "PERMISSION_DENIED_NOT_IN_ROOM",
  "PERMISSION_DENIED_NOT_HOST",
]);

/**
 * CaseStartReason
 */
export const zCaseStartReason = z.enum(["STARTED"]);

/**
 * CaseStartRequest
 */
export const zCaseStartRequest = z.object({
  red_player_count: z.optional(z.union([z.int().gte(0).lt(8), z.null()])),
});

/**
 * CaseStartSuccessCode
 */
export const zCaseStartSuccessCode = z.enum(["OK"]);

/**
 * CommonErrorCode
 */
export const zCommonErrorCode = z.enum(["VALIDATION_ERROR"]);

/**
 * Envelope[ActionReceipt, BlueVoteSuccessCode]
 */
export const zEnvelopeActionReceiptBlueVoteSuccessCode = z.object({
  ok: z.boolean(),
  code: zBlueVoteSuccessCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zActionReceipt, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Envelope[NoneType, ActionConflictCode]
 */
export const zEnvelopeNoneTypeActionConflictCode = z.object({
  ok: z.boolean(),
  code: zActionConflictCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Envelope[NoneType, ActionForbiddenCode]
 */
export const zEnvelopeNoneTypeActionForbiddenCode = z.object({
  ok: z.boolean(),
  code: zActionForbiddenCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Envelope[NoneType, CaseStartConflictCode]
 */
export const zEnvelopeNoneTypeCaseStartConflictCode = z.object({
  ok: z.boolean(),
  code: zCaseStartConflictCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Envelope[NoneType, CaseStartForbiddenCode]
 */
export const zEnvelopeNoneTypeCaseStartForbiddenCode = z.object({
  ok: z.boolean(),
  code: zCaseStartForbiddenCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Envelope[NoneType, CommonErrorCode]
 */
export const zEnvelopeNoneTypeCommonErrorCode = z.object({
  ok: z.boolean(),
  code: zCommonErrorCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Envelope[NoneType, Union[ActionConflictCode, BlueVoteConflictCode]]
 */
export const zEnvelopeNoneTypeUnionActionConflictCodeBlueVoteConflictCode =
  z.object({
    ok: z.boolean(),
    code: z.union([zActionConflictCode, zBlueVoteConflictCode]),
    message: z.optional(z.union([z.string(), z.null()])),
    data: z.optional(z.null()),
    meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  });

/**
 * ForceSkipDiscussSuccessCode
 */
export const zForceSkipDiscussSuccessCode = z.enum(["OK"]);

/**
 * Envelope[ActionReceipt, ForceSkipDiscussSuccessCode]
 */
export const zEnvelopeActionReceiptForceSkipDiscussSuccessCode = z.object({
  ok: z.boolean(),
  code: zForceSkipDiscussSuccessCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zActionReceipt, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * GuestLoginData
 *
 * If in_case is true, current_case_id must be provided; otherwise it must be null.
 */
export const zGuestLoginData = z.object({
  id: z.uuid(),
  username: z.string(),
  in_case: z.boolean(),
  current_case_id: z.optional(z.union([z.uuid(), z.null()])),
});

/**
 * GuestLoginRequest
 */
export const zGuestLoginRequest = z.object({
  username: z.string().min(3).max(32),
});

/**
 * InitBlueVoteBadRequestCode
 */
export const zInitBlueVoteBadRequestCode = z.enum(["INVALID_TARGET_SEAT_NO"]);

/**
 * Envelope[NoneType, InitBlueVoteBadRequestCode]
 */
export const zEnvelopeNoneTypeInitBlueVoteBadRequestCode = z.object({
  ok: z.boolean(),
  code: zInitBlueVoteBadRequestCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * InitBlueVoteConflictCode
 */
export const zInitBlueVoteConflictCode = z.enum([
  "DISCUSS_REJECTED_NO_TOKEN_INIT",
  "DISCUSS_REJECTED_SELF_VOTE_INIT",
]);

/**
 * Envelope[NoneType, Union[ActionConflictCode, InitBlueVoteConflictCode]]
 */
export const zEnvelopeNoneTypeUnionActionConflictCodeInitBlueVoteConflictCode =
  z.object({
    ok: z.boolean(),
    code: z.union([zActionConflictCode, zInitBlueVoteConflictCode]),
    message: z.optional(z.union([z.string(), z.null()])),
    data: z.optional(z.null()),
    meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  });

/**
 * InitBlueVoteNotFoundCode
 */
export const zInitBlueVoteNotFoundCode = z.enum(["TARGET_SEAT_EMPTY"]);

/**
 * Envelope[NoneType, InitBlueVoteNotFoundCode]
 */
export const zEnvelopeNoneTypeInitBlueVoteNotFoundCode = z.object({
  ok: z.boolean(),
  code: zInitBlueVoteNotFoundCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * InitBlueVoteRequest
 *
 * POST /api/cases/current/init-blue-vote 요청 바디.
 *
 * 의미:
 * - DISCUSS phase에서 blue-vote의 대상 seat_no를 지정하여 VOTE phase 시작을 요청한다.
 *
 * 필드 해석:
 * - target_seat_no: 유효한 seat_no(SeatNo)
 */
export const zInitBlueVoteRequest = z.object({
  target_seat_no: z.int().gte(0).lt(8),
});

/**
 * InitBlueVoteSuccessCode
 */
export const zInitBlueVoteSuccessCode = z.enum(["OK"]);

/**
 * Envelope[ActionReceipt, InitBlueVoteSuccessCode]
 */
export const zEnvelopeActionReceiptInitBlueVoteSuccessCode = z.object({
  ok: z.boolean(),
  code: zInitBlueVoteSuccessCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zActionReceipt, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * JoinRoomCode
 */
export const zJoinRoomCode = z.enum(["OK"]);

/**
 * JoinRoomReason
 */
export const zJoinRoomReason = z.enum(["JOINED", "ALREADY_JOINED"]);

/**
 * KickUserCode
 */
export const zKickUserCode = z.enum(["OK"]);

/**
 * KickUserReason
 */
export const zKickUserReason = z.enum(["KICKED", "NOT_IN_ROOM"]);

/**
 * LeaveRoomCode
 */
export const zLeaveRoomCode = z.enum(["OK"]);

/**
 * LeaveRoomReason
 */
export const zLeaveRoomReason = z.enum(["LEFT", "ALREADY_LEFT"]);

/**
 * LoginCode
 */
export const zLoginCode = z.enum(["OK"]);

/**
 * Envelope[GuestLoginData, LoginCode]
 */
export const zEnvelopeGuestLoginDataLoginCode = z.object({
  ok: z.boolean(),
  code: zLoginCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zGuestLoginData, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * LogoutCode
 */
export const zLogoutCode = z.enum(["OK"]);

/**
 * Envelope[NoneType, LogoutCode]
 */
export const zEnvelopeNoneTypeLogoutCode = z.object({
  ok: z.boolean(),
  code: zLogoutCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * RedVoteBadRequestCode
 */
export const zRedVoteBadRequestCode = z.enum(["INVALID_TARGET_SEAT_NO"]);

/**
 * Envelope[NoneType, RedVoteBadRequestCode]
 */
export const zEnvelopeNoneTypeRedVoteBadRequestCode = z.object({
  ok: z.boolean(),
  code: zRedVoteBadRequestCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * RedVoteConflictCode
 */
export const zRedVoteConflictCode = z.enum(["NIGHT_REJECTED_SELF_VOTE"]);

/**
 * Envelope[NoneType, Union[ActionConflictCode, RedVoteConflictCode]]
 */
export const zEnvelopeNoneTypeUnionActionConflictCodeRedVoteConflictCode =
  z.object({
    ok: z.boolean(),
    code: z.union([zActionConflictCode, zRedVoteConflictCode]),
    message: z.optional(z.union([z.string(), z.null()])),
    data: z.optional(z.null()),
    meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
  });

/**
 * RedVoteNotFoundCode
 */
export const zRedVoteNotFoundCode = z.enum(["TARGET_SEAT_EMPTY"]);

/**
 * Envelope[NoneType, RedVoteNotFoundCode]
 */
export const zEnvelopeNoneTypeRedVoteNotFoundCode = z.object({
  ok: z.boolean(),
  code: zRedVoteNotFoundCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.null()),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * RedVoteRequest
 *
 * POST /api/cases/current/red-vote 요청 바디.
 *
 * 의미:
 * - NIGHT phase에서 red-vote 대상 seat_no를 지정한다.
 * - skip인 경우 target_seat_no를 null로 전송한다.
 *
 * 필드 해석:
 * - target_seat_no: 유효한 seat_no(SeatNo), 또는 skip(null)
 */
export const zRedVoteRequest = z.object({
  target_seat_no: z.optional(z.union([z.int().gte(0).lt(8), z.null()])),
});

/**
 * RedVoteSuccessCode
 */
export const zRedVoteSuccessCode = z.enum(["OK"]);

/**
 * Envelope[ActionReceipt, RedVoteSuccessCode]
 */
export const zEnvelopeActionReceiptRedVoteSuccessCode = z.object({
  ok: z.boolean(),
  code: zRedVoteSuccessCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zActionReceipt, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * Subject
 */
export const zSubject = z.enum(["ME", "USER"]);

/**
 * Target
 */
export const zTarget = z.enum(["ROOM", "CASE"]);

/**
 * CaseStartMutation
 *
 * POST /api/rooms/current/case-start 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 현재 사용자가 ROOM에서 case 시작을 시도한 "성공 결과"를 나타낸다.
 * - 권한/조건 불충족으로 시작에 실패한 경우는 403/409로 분리되며, body의 data는 null이다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == ME
 * - subject_id == None
 * - on_target == True (요청 이후 room에 case가 존재)
 * - changed == True (요청으로 인해 실제로 case 시작이 발생)
 * - reason == STARTED
 */
export const zCaseStartMutation = z.object({
  target: z.optional(zTarget).default("ROOM"),
  subject: z.optional(zSubject).default("ME"),
  subject_id: z.optional(z.null()),
  on_target: z.optional(z.literal(true)).default(true),
  changed: z.optional(z.literal(true)).default(true),
  reason: z.optional(zCaseStartReason).default("STARTED"),
});

/**
 * Envelope[CaseStartMutation, CaseStartSuccessCode]
 */
export const zEnvelopeCaseStartMutationCaseStartSuccessCode = z.object({
  ok: z.boolean(),
  code: zCaseStartSuccessCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zCaseStartMutation, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * JoinRoomMutation
 *
 * POST /api/rooms/{room_id}/join 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 현재 사용자가 특정 ROOM에 참가를 시도한 결과를 나타낸다.
 * - 이미 참가 중인 경우에도 200으로 응답하며, changed=False로 표현한다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == ME
 * - subject_id == None
 * - on_target == True (요청 이후 항상 방에 속한 상태)
 * - changed: 실제로 참가 상태가 변경되었는지 여부
 * - reason: JOINED | ALREADY_JOINED
 */
export const zJoinRoomMutation = z.object({
  target: z.optional(zTarget).default("ROOM"),
  subject: z.optional(zSubject).default("ME"),
  subject_id: z.optional(z.null()),
  on_target: z.optional(z.literal(true)).default(true),
  changed: z.boolean(),
  reason: zJoinRoomReason,
});

/**
 * Envelope[JoinRoomMutation, JoinRoomCode]
 */
export const zEnvelopeJoinRoomMutationJoinRoomCode = z.object({
  ok: z.boolean(),
  code: zJoinRoomCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zJoinRoomMutation, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * KickUserMutation
 *
 * POST /api/rooms/current/users/{user_id}/kick 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 특정 USER를 현재 ROOM에서 내보내기를 시도한 결과를 나타낸다.
 * - 대상이 해당 ROOM에 없더라도 200으로 응답하며, changed=False로 표현한다.
 * - 이 mutation은 대상 room에서 실제 멤버십이 제거되었는지만 보장한다.
 * 대상 유저의 다른 room 소속 여부는 반환하지 않는다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == USER
 * - subject_id: 대상 USER의 식별자(UUID)
 * - on_target == False (요청 이후 대상은 해당 ROOM에 속하지 않음)
 * - changed: 실제로 멤버십이 제거되었는지 여부
 * - reason: KICKED | NOT_IN_ROOM
 */
export const zKickUserMutation = z.object({
  target: z.optional(zTarget).default("ROOM"),
  subject: z.optional(zSubject).default("USER"),
  subject_id: z.uuid(),
  on_target: z.optional(z.literal(false)).default(false),
  changed: z.boolean(),
  reason: zKickUserReason,
});

/**
 * Envelope[KickUserMutation, KickUserCode]
 */
export const zEnvelopeKickUserMutationKickUserCode = z.object({
  ok: z.boolean(),
  code: zKickUserCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zKickUserMutation, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * LeaveRoomMutation
 *
 * POST /api/rooms/current/leave 성공(200) 시 반환되는 mutation 데이터.
 *
 * 의미:
 * - 현재 사용자가 ROOM에서 나가기를 시도한 결과를 나타낸다.
 * - 이미 방에 속해 있지 않은 경우에도 200으로 응답하며, changed=False로 표현한다.
 *
 * 필드 해석:
 * - target == ROOM
 * - subject == ME
 * - subject_id == None
 * - on_target == False (요청 이후 항상 방에 속하지 않은 상태)
 * - changed: 실제로 멤버십이 변경되었는지 여부
 * - reason: LEFT | ALREADY_LEFT
 */
export const zLeaveRoomMutation = z.object({
  target: z.optional(zTarget).default("ROOM"),
  subject: z.optional(zSubject).default("ME"),
  subject_id: z.optional(z.null()),
  on_target: z.optional(z.literal(false)).default(false),
  changed: z.boolean(),
  reason: zLeaveRoomReason,
});

/**
 * Envelope[LeaveRoomMutation, LeaveRoomCode]
 */
export const zEnvelopeLeaveRoomMutationLeaveRoomCode = z.object({
  ok: z.boolean(),
  code: zLeaveRoomCode,
  message: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(z.union([zLeaveRoomMutation, z.null()])),
  meta: z.optional(z.union([z.record(z.string(), z.unknown()), z.null()])),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

export const zGuestLoginApiV1AuthGuestLoginPostData = z.object({
  body: zGuestLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Temporary API. Creates/returns a guest user session. (MVP stub: no JWT cookies are issued yet, and no leave_room side-effect is triggered.)
 */
export const zGuestLoginApiV1AuthGuestLoginPostResponse =
  zEnvelopeGuestLoginDataLoginCode;

export const zLogoutApiV1AuthLogoutPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Temporary API. Logs out the current session. (MVP stub: does not clear cookies yet, and no leave_room side-effect is triggered.)
 */
export const zLogoutApiV1AuthLogoutPostResponse = zEnvelopeNoneTypeLogoutCode;

export const zBlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostData = z.object(
  {
    body: zBlueVoteRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  },
);

/**
 * Response Blue Vote Api V1 Cases Current Phases Current Blue Vote Post
 *
 * Successful Response
 */
export const zBlueVoteApiV1CasesCurrentPhasesCurrentBlueVotePostResponse =
  z.union([
    zEnvelopeActionReceiptBlueVoteSuccessCode,
    zEnvelopeNoneTypeUnionActionConflictCodeBlueVoteConflictCode,
    zEnvelopeNoneTypeActionForbiddenCode,
  ]);

export const zForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostData =
  z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  });

/**
 * Response Force Skip Discuss Api V1 Cases Current Phases Current Force Skip Discuss Post
 *
 * Successful Response
 */
export const zForceSkipDiscussApiV1CasesCurrentPhasesCurrentForceSkipDiscussPostResponse =
  z.union([
    zEnvelopeActionReceiptForceSkipDiscussSuccessCode,
    zEnvelopeNoneTypeActionConflictCode,
    zEnvelopeNoneTypeActionForbiddenCode,
  ]);

export const zInitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostData =
  z.object({
    body: zInitBlueVoteRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  });

/**
 * Response Init Blue Vote Api V1 Cases Current Phases Current Init Blue Vote Post
 *
 * Successful Response
 */
export const zInitBlueVoteApiV1CasesCurrentPhasesCurrentInitBlueVotePostResponse =
  z.union([
    zEnvelopeActionReceiptInitBlueVoteSuccessCode,
    zEnvelopeNoneTypeInitBlueVoteBadRequestCode,
    zEnvelopeNoneTypeUnionActionConflictCodeInitBlueVoteConflictCode,
    zEnvelopeNoneTypeInitBlueVoteNotFoundCode,
    zEnvelopeNoneTypeActionForbiddenCode,
  ]);

export const zRedVoteApiV1CasesCurrentPhasesCurrentRedVotePostData = z.object({
  body: zRedVoteRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Red Vote Api V1 Cases Current Phases Current Red Vote Post
 *
 * Successful Response
 */
export const zRedVoteApiV1CasesCurrentPhasesCurrentRedVotePostResponse =
  z.union([
    zEnvelopeActionReceiptRedVoteSuccessCode,
    zEnvelopeNoneTypeRedVoteBadRequestCode,
    zEnvelopeNoneTypeRedVoteNotFoundCode,
    zEnvelopeNoneTypeActionForbiddenCode,
    zEnvelopeNoneTypeUnionActionConflictCodeRedVoteConflictCode,
  ]);

export const zJoinRoomApiV1RoomsRoomIdJoinPostData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    room_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zJoinRoomApiV1RoomsRoomIdJoinPostResponse =
  zEnvelopeJoinRoomMutationJoinRoomCode;

export const zLeaveRoomApiV1RoomsCurrentLeavePostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLeaveRoomApiV1RoomsCurrentLeavePostResponse =
  zEnvelopeLeaveRoomMutationLeaveRoomCode;

export const zKickUserApiV1RoomsCurrentUsersUserIdKickPostData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zKickUserApiV1RoomsCurrentUsersUserIdKickPostResponse =
  zEnvelopeKickUserMutationKickUserCode;

export const zCaseStartApiV1RoomsCurrentCaseStartPostData = z.object({
  body: zCaseStartRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zCaseStartApiV1RoomsCurrentCaseStartPostResponse =
  zEnvelopeCaseStartMutationCaseStartSuccessCode;

export const zHealthApiHealthGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zRoomStateSseRtV1SseRoomsCurrentGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.optional(
    z.object({
      "X-User-Id": z.optional(z.union([z.string(), z.null()])),
      "X-Room-Id": z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});
